services:
  database:
    container_name: 'integration-flight-booking-postgres'
    image: 'postgres:14'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: integration-flight-booking
    volumes:
      - ./sql/int-data:/var/lib/postgresql/data

volumes:
  db-data:
